[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
erebrus = "Bhvt1zhb14KRwXyan3cMZ52qwyyJP7Cji5HJrQrdmkAk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://rpc.devnet.soo.network/rpc"
wallet = "~/.config/solana/id.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
