[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
<<<<<<< HEAD:Eclipse/erebrus_v1/Anchor.toml
erebrus_v1 = "6HuaUmMRvSfbgXAqzbCLZCW39rGkzoKUeWhjPc4eyEJ8"
=======
erebrus = "6qnn1UZoy688fpTNqdkhiEogHFbqephGRNGy8nz3zY5o"
>>>>>>> main:Solana/erebrus/Anchor.toml

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.mainnet-beta.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
