[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
<<<<<<< HEAD:Solana/erebrus_v1/Anchor.toml
erebrus_v1 = "6HuaUmMRvSfbgXAqzbCLZCW39rGkzoKUeWhjPc4eyEJ8"
=======
erebrus = "E67ritmxgYPVP9SbcXp5KQx2s5zrx3JzKPg6bzqgkcEZ"
>>>>>>> main:Eclipse/erebrus/Anchor.toml

[registry]
url = "https://api.apr.dev"

[provider]
<<<<<<< HEAD:Solana/erebrus_v1/Anchor.toml
cluster = "Localnet"
=======
cluster = "https://mainnetbeta-rpc.eclipse.xyz"
>>>>>>> main:Eclipse/erebrus/Anchor.toml
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

