[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
erebrus = "E67ritmxgYPVP9SbcXp5KQx2s5zrx3JzKPg6bzqgkcEZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://mainnetbeta-rpc.eclipse.xyz"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

